name: OpenDeckedOut
version: 0.1.0
main: com.github.advancedwipe.OpenDeckedOut
description: An example plugin
author: AdvancedWipe
website: https://papermc.io
api-version: '1.20'
commands:
  opendeckedout:
    description: Your description
    usage: /<command>
    aliases:
      - odo
      - do
