name: OpenDeckedOut
version: 0.1.0
main: com.github.advancedwipe.opendeckedout.OpenDeckedOut
description: A plugin that implements the famous DeckedOut by TangoTek on a server.
author: AdvancedWipe
website: https://github.com/AdvancedWipe/opendeckedout
api-version: '1.20'
permissions:
  deckedout.command.join:
    default: "true"
  deckedout.command.leave:
    default: "true"